# Generated code do not commit.
file(TO_CMAKE_PATH "C:\\src\\Flutter\\flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "C:\\repos\\DSI_grupo05_2025.1" PROJECT_DIR)

set(FLUTTER_VERSION "0.1.0" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 0 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 0 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=C:\\src\\Flutter\\flutter"
  "PROJECT_DIR=C:\\repos\\DSI_grupo05_2025.1"
  "FLUTTER_ROOT=C:\\src\\Flutter\\flutter"
  "FLUTTER_EPHEMERAL_DIR=C:\\repos\\DSI_grupo05_2025.1\\windows\\flutter\\ephemeral"
  "PROJECT_DIR=C:\\repos\\DSI_grupo05_2025.1"
  "FLUTTER_TARGET=C:\\repos\\DSI_grupo05_2025.1\\lib\\main.dart"
  "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzIuMg==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049OGRlZmFhNzFhNw==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049MTA5MTUwODkzOQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My44LjE="
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=C:\\repos\\DSI_grupo05_2025.1\\.dart_tool\\package_config.json"
)
